language: csharp
sudo: required
dist: trusty
dotnet: 2.0.3
mono:
  - 5.4.1
  - latest
os:
  - linux
  - osx
before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags 
script:
  - ./build.sh
cache:
  directories:
    - src/packages
    - tools
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true