language: csharp
solution: src/GitVersion.sln
sudo: false
install:
  - mkdir -p src/.nuget
  - wget -NO src/.nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script:
	- mono --runtime=v4.0.30319 "src/.nuget/nuget.exe" Restore "./src/GitVersion.sln"
	- xbuild "./src/GitVersion.sln" 
	- mono --debug --runtime=v4.0.30319 ./src/packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/GitVersionTask.Tests/bin/Debug/GitVersionTask.Tests.dll ./src/GitVersionCore.Tests/bin/Debug/GitVersionCore.Tests.dll ./src/GitVersionTask.Tests/bin/Debug/GitVersionTask.Tests.dll ./src/GitVersionExe.Tests/bin/Debug/GitVersionExe.Tests.dll -nodots