language: csharp
solution: src/GitVersion.sln
sudo: false
install:
  - nuget restore src/GitVersion.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory ./src/packages
script:
  - xbuild "./src/GitVersion.sln" /property:Configuration="Debug" /verbosity:detailed
  - mono --debug --runtime=v4.0.30319 ./src/packages/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe ./src/GitVersionTask.Tests/bin/Debug/GitVersionTask.Tests.dll ./src/GitVersionCore.Tests/bin/Debug/GitVersionCore.Tests.dll ./src/GitVersionTask.Tests/bin/Debug/GitVersionTask.Tests.dll ./src/GitVersionExe.Tests/bin/Debug/GitVersionExe.Tests.dll
