language: csharp
solution: src/GitVersion.sln
sudo: false
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - chmod +x .nuget/nuget.exe
  - .nuget/nuget.exe
install:
  - .nuget/nuget.exe restore src/GitVersion.sln -Verbosity detailed
  - .nuget/nuget.exe install NUnit.Runners -Version 3.2.1 -OutputDirectory ./src/packages
script:
  - xbuild "./src/GitVersion.sln" /property:Configuration="Debug" /verbosity:detailed
after_script:
  - mono --debug --runtime=v4.0.30319 ./src/packages/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe ./src/GitVersionTask.Tests/bin/Debug/GitVersionTask.Tests.dll ./src/GitVersionCore.Tests/bin/Debug/GitVersionCore.Tests.dll ./src/GitVersionTask.Tests/bin/Debug/GitVersionTask.Tests.dll ./src/GitVersionExe.Tests/bin/Debug/GitVersionExe.Tests.dll -where "cat != NoMono"
