language: csharp
sudo: required
dist: trusty
dotnet: 2.1.4
mono:
  - 5.4.0
os:
  - linux
  - osx
before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags 
script:
  - ./build.sh
cache:
  directories:
    - src/packages
    - tools