image: Visual Studio 2017

assembly_info:
  patch: false

configuration:
  - Debug
install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%

build_script:
  - pwsh: ./run.ps1 -script run.cake -target Default

test: off
skip_tags: true
