jobs:
- job: macOS
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.401'
    inputs:
      version: 2.1.401
  - powershell: ./run.ps1 -script build.cake -target Unix
    displayName: 'Cake build'
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.401'
    inputs:
      version: 2.1.401
  - powershell: ./run.ps1 -script build.cake -target Unix
    displayName: 'Cake build'
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.401'
    inputs:
      version: 2.1.401
  - powershell: ./run.ps1 -script build.cake
    displayName: 'Cake build'
